language: node_js

node_js:
  - 0.10

before_script:
#  - npm link
#  - mkdir -p shippable/codecoverage

after_success:
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate < ./coverage/lcov.info


deploy:
  provider: npm
  email: 
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: Yoobic/install-mac
