os: osx

osx_image: xcode8.3

language: objective-c

cache:
   directories:
     - node_modules

install:
  - zsh install.sh

script:
  - source ~/.zshrc
  - which -s node || nvm use default
  - zsh test.sh
