os: osx

osx_image: xcode8.3

language: objective-c

cache:
   directories:
     - node_modules

install:
  - zsh install.sh

script:
  - source ~/.zshrc
  - nvm use `nvm version-remote --lts`
  - zsh test.sh
