name: Test

on: 
  push:
env:
  CI: true
defaults:
  run:
    shell: zsh {0}
jobs: 
  test: 
    name: test
    runs-on: macos-latest
    timeout-minutes: 30
    steps: 
    - name: check zsh
      run: which zsh
    - uses: actions/checkout@v2
    - name: install
      run: zsh install.sh
#    - name: source
#      run: source ~/.zshrc
    - name: node
      run: which -s node || nvm use default
    - name: test
      run: zsh test.sh



